name: stale
on:
  schedule:
    - cron: "30 1 * * *"
permissions:
  contents: read

jobs:
  stale:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: lemonfiber/spec/.github/workflows/stale.yml@bb95f42d7630f689a1c5ec05cc39fb82476ace94 # v1.0.4
